DROP DATABASE IF EXISTS todolist_db;
CREATE DATABASE todolist_db;

\c todolist_db;

CREATE TABLE todos (
  id SERIAL PRIMARY KEY,
  todo VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id SERIAL , 
  name VARCHAR(255) NOT NULL, 
  email VARCHAR(255) NOT NULL UNIQUE, 
  password VARCHAR(255) NOT NULL, 
  PRIMARY KEY (id)
  );
